.\"	$OpenBSD: btrace.8,v 1.11 2025/10/05 22:31:54 sashan Exp $
.\"
.\" Copyright (c) 2019 Martin Pieuchot <mpi@openbsd.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: October 5 2025 $
.Dt BTRACE 8
.Os
.Sh NAME
.Nm btrace
.Nd bug tracer
.Sh SYNOPSIS
.Nm btrace
.Op Fl lnqv
.Ar programfile | Fl e Ar program
.Op Ar argument ...
.Sh DESCRIPTION
The
.Nm
utility provides an interface to inspect the internals of the system and
programs.
It interprets the
.Xr bt 5
program read from the
.Ar programfile ,
passing the optional
.Ar arguments
to it, and communicates with the dynamic tracer device
using the interface described in
.Xr dt 4 .
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl e Ar program
Execute the
.Ar program
specified as the option argument instead of reading a program from a file.
In this case, all non-option
.Ar arguments
are passed through to the
.Ar program .
.It Fl l
List all available probes.
.It Fl n
No action.
Parse the program and then exit.
.It Fl q
Quiet mode.
Suppress informational messages.
.It Fl v
Verbose mode.
Causes
.Nm
to print debugging messages.
Multiple
.Fl v
options increase the verbosity.
The maximum is 2.
.El
.Sh FILES
.Bl -tag -width "/usr/share/btrace/XXXX" -compact
.It Pa /usr/share/btrace/*
collection of useful
.Nm
programs
.El
.Sh EXAMPLES
Trace all kernel memory allocation functions, showing arguments:
.Pp
.Dl # btrace -e 'kprobe:*alloc* { printf("%s(%s)\en", probe, arg0); }'
.Pp
Trace return values from a kernel function:
.Pp
.Dl # btrace -e 'kretprobe:malloc { printf("malloc returned %s\en", retval); }'
.Pp
Count function calls matching a pattern:
.Pp
.Dl # btrace -e 'kprobe:vm_* { @[probe] = count(); }'
.Pp
Profile kernel stacks at 99 Hz:
.Pp
.Dl # btrace -e 'profile:hz:99 { @[kstack] = count(); }'
.Pp
Print a map every 5 seconds:
.Pp
.Dl # btrace -e 'interval:s:5 { print(@); }'
.Pp
Count syscalls by process name:
.Pp
.Dl # btrace -e 'syscall:*:entry { @[comm] = count(); }'
.Pp
Histogram of syscall latency:
.Pp
.Dl # btrace -e 'syscall:*:entry { @start[tid] = nsecs; } syscall:*:return /@start[tid]/ { @ = hist(nsecs - @start[tid]); delete(@start[tid]); }'
.Sh EXIT STATUS
.Ex -std 
.Sh SEE ALSO
.Xr dt 4 ,
.Xr bt 5
.Sh HISTORY
The
.Nm
utility first appeared in
.Ox 6.7 .
.Sh AUTHORS
.An Martin Pieuchot Aq Mt mpi@openbsd.org
